# Generated by Django 3.2 on 2021-05-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='building',
        ),
    ]
