# Generated by Django 3.2 on 2021-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_society_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='building',
            field=models.ManyToManyField(to='core.Building'),
        ),
    ]
