# Generated by Django 3.2 on 2021-05-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_society_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='flat',
            field=models.ManyToManyField(to='core.Flat'),
        ),
    ]
