# Generated by Django 3.2 on 2021-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210507_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
