# Generated by Django 3.2 on 2021-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_flat_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat',
            field=models.CharField(max_length=30),
        ),
    ]
