# Generated by Django 3.2 on 2021-05-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_flat_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='flat',
            new_name='flat_no',
        ),
    ]
