# Generated by Django 3.2 on 2021-05-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0002_alter_building_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build', to='core1.society'),
        ),
    ]
