# Generated by Django 3.2 on 2021-05-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core1', '0003_alter_building_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='core1.building'),
        ),
    ]
